repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/quacks-yaks/pre-commit
    rev: v0.1.27
    hooks:
      - id: terragrunt-hclfmt
        types: [file]
        files: ^terragrunt/.*\.hcl$
      - id: terraform-fmt
        types: [file]
        files: ^terraform/modules/.*\.tf$
      - id: terraform-validate
